language: python

python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=./webtest_sanic tests

after_success:
  - codecov
